sum_vect:
	g++ -g -Wall -fopenmp -o sum_vect.out sum_vect.cpp
	./sum_vect.out 4 1000000

mat_mult:
	g++ -g -Wall -fopenmp -o mat_mult.out mat_mult.cpp
	./mat_mult.out 4 1000 1000 1000

random_generator:
	g++ -g -Wall -fopenmp -o random_generator.out random_generator.cpp
	./random_generator.out 2

clean:
	rm *.out
